name: cloudwatch
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  built_value: ^8.1.3
  google_fonts: ^2.2.0
  http: ^0.13.4
  json_serializable: ^6.1.3
  cupertino_icons: ^1.0.2
  get: 4.6.1
  get_storage: ^2.0.3
  get_test: 
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.1.5
  json_serializable: ^6.1.0
  mockito:
  flutter_lints: ^1.0.0
  parallax_rain: ^1.1.0
  particles_flutter: ^0.1.4
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/testJson/city.json

